name: Build Extension

on:
  push:
    branches:
      - main
      - rc
      - dev
      - feature/*
  workflow_dispatch:

env:
    IS_RELEASE: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
    IS_RC: ${{ github.ref == 'refs/heads/rc' }}
    IS_BETA: ${{ github.ref == 'refs/heads/dev' }}

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      environment: Dev
      
      steps:
        # Checkout the repository
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        # Set up Node.js
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18'
              
        - name: SemVer
          id: git-semver
          uses: codedesignplus/semver-git-version@v0.1.10
          with:
            folder: ${{github.workspace}}
            release-branch: 'main'
            release-candidate-branch: 'rc'
            beta-branch: 'dev'
            major-identifier: 'breaking'
            minor-identifier: 'feat'
            prefix: 'v'
            dir-affected: ./
            previous-version: true
            new-version: true

        - name: Print Output
          id: output
          run: |
            echo Previous Tag "${{ steps.git-semver.outputs.previous-tag }}"
            echo Previous Version "${{ steps.git-semver.outputs.previous-version }}"
            echo Previous Version Prefix "${{ steps.git-semver.outputs.previous-version-prefix }}"
            echo New Version "${{steps.git-semver.outputs.new-version}}"
            echo New Version Prefix "${{steps.git-semver.outputs.new-version-prefix}}"

        - name: Set version
          run: npm version ${{ steps.git-semver.outputs.new-version }} --no-git-tag-version
      

        # Install dependencies
        - name: Install dependencies
          run: npm install
        
        # Install vsce
        - name: Install vsce
          run: npm install -g @vscode/vsce

        # Build the extension
        - name: Build the extension
          run: vsce package

        # Publish to VS Code Marketplace
        - name: Publish to VS Code Marketplace
          env:
            VSCE_PAT: ${{ secrets.VSCE_PAT }}
          run: vsce publish

        - name: Push tag
          id: push_tag
          if: env.IS_RELEASE == 'true' || env.IS_RC == 'true' || env.IS_BETA == 'true'
          uses: mathieudutour/github-tag-action@v6.1
          with:
            custom_tag: ${{ steps.git-semver.outputs.new-version }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
    
        - name: Build Changelog
          if: env.IS_RELEASE == 'true' || env.IS_RC == 'true'
          id: build_changelog
          uses: mikepenz/release-changelog-builder-action@v4
          with:
            configuration: "${{ github.workspace }}/.github/settings/configuration.json"
            fromTag: ${{ steps.git-semver.outputs.previous-version-prefix }}
            toTag: ${{ steps.git-semver.outputs.new-version-prefix }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
        - name: Create GitHub Release
          if: env.IS_RELEASE == 'true' || env.IS_RC == 'true'
          uses: mikepenz/action-gh-release@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            tag_name: ${{ steps.git-semver.outputs.new-version-prefix }}
            name: "CodeDesignPlus.Net.Sdk@${{ steps.git-semver.outputs.new-version-prefix }}"
            body: ${{ steps.build_changelog.outputs.changelog }}
            prerelease: ${{ contains(github.ref, 'rc') || contains(github.ref, 'dev') }}